server:
  port: 9999
logging:
  level:
    qr.program.microservice: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: nacos:8848 # nacos地址
    gateway:
      routes:
        - id: user-service # 路由标示，必须唯一
          uri: lb://userservice # 路由的目标地址, lb: loadBalance
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: order-service
          uri: lb://orderservice
          # 路由断言规则：https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/#the-before-route-predicate-factory
          predicates:
            - Path=/order/**
            - Before=2032-01-20T17:42:47.789-07:00[America/Denver]
      default-filters: # 全局路由过滤器，处理请求或响应
        - AddRequestHeader=Greet, 你好哇
      globalcors: # 全局的跨域处理
        # 解决options请求被拦截问题
        # 浏览器在发送非简单请求时会发送一个 options 类型的预检请求，用于查询服务器的跨域要求
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期