server:
  port: 10000
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/cloud_order?useSSL=false
    username: xx
    password: xx
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: nacos:8848 # nacos服务地址
      discovery:
        namespace: 4d6ce343-9e1b-44df-a90f-2cf2b6b3d177 # dev环境
        ephemeral: false # 是否是临时实例
mybatis:
  type-aliases-package: qr.program.microservice.order.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    qr.program.microservice: info
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: # 指定饥饿加载的服务名称
      - userservice
feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数